/*
  # Add Primary Keys to Stripe Tables

  1. Database Changes
    - Add primary key columns to `stripe_customers`, `stripe_orders`, and `stripe_subscriptions` tables
    - These tables currently lack primary keys, preventing row deletion operations
    - Primary keys will be auto-incrementing integers for proper row identification

  2. Benefits
    - Enables row deletion operations in Supabase dashboard
    - Improves database performance with proper indexing
    - Follows PostgreSQL best practices for table design
    - Maintains data integrity with unique row identification

  3. Important Notes
    - Uses `GENERATED BY DEFAULT AS IDENTITY` for compatibility with existing data
    - Preserves all existing data and relationships
    - Primary keys are separate from business logic identifiers (customer_id, subscription_id, etc.)
*/

-- Add primary key to stripe_customers table
DO $$
BEGIN
  -- Check if id column already has a primary key constraint
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints 
    WHERE table_name = 'stripe_customers' 
    AND constraint_type = 'PRIMARY KEY'
  ) THEN
    -- Add primary key constraint to existing id column
    ALTER TABLE stripe_customers ADD CONSTRAINT stripe_customers_pkey PRIMARY KEY (id);
    
    -- Ensure the id column is properly configured as identity
    ALTER TABLE stripe_customers ALTER COLUMN id SET GENERATED BY DEFAULT AS IDENTITY;
    
    RAISE NOTICE 'Added primary key to stripe_customers table';
  ELSE
    RAISE NOTICE 'Primary key already exists on stripe_customers table';
  END IF;
END $$;

-- Add primary key to stripe_orders table
DO $$
BEGIN
  -- Check if id column already has a primary key constraint
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints 
    WHERE table_name = 'stripe_orders' 
    AND constraint_type = 'PRIMARY KEY'
  ) THEN
    -- Add primary key constraint to existing id column
    ALTER TABLE stripe_orders ADD CONSTRAINT stripe_orders_pkey PRIMARY KEY (id);
    
    -- Ensure the id column is properly configured as identity
    ALTER TABLE stripe_orders ALTER COLUMN id SET GENERATED BY DEFAULT AS IDENTITY;
    
    RAISE NOTICE 'Added primary key to stripe_orders table';
  ELSE
    RAISE NOTICE 'Primary key already exists on stripe_orders table';
  END IF;
END $$;

-- Add primary key to stripe_subscriptions table
DO $$
BEGIN
  -- Check if id column already has a primary key constraint
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints 
    WHERE table_name = 'stripe_subscriptions' 
    AND constraint_type = 'PRIMARY KEY'
  ) THEN
    -- Add primary key constraint to existing id column
    ALTER TABLE stripe_subscriptions ADD CONSTRAINT stripe_subscriptions_pkey PRIMARY KEY (id);
    
    -- Ensure the id column is properly configured as identity
    ALTER TABLE stripe_subscriptions ALTER COLUMN id SET GENERATED BY DEFAULT AS IDENTITY;
    
    RAISE NOTICE 'Added primary key to stripe_subscriptions table';
  ELSE
    RAISE NOTICE 'Primary key already exists on stripe_subscriptions table';
  END IF;
END $$;

-- Verify primary keys were added successfully
DO $$
DECLARE
  pk_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO pk_count
  FROM information_schema.table_constraints 
  WHERE table_name IN ('stripe_customers', 'stripe_orders', 'stripe_subscriptions')
  AND constraint_type = 'PRIMARY KEY';
  
  RAISE NOTICE 'Total primary key constraints on Stripe tables: %', pk_count;
  
  IF pk_count = 3 THEN
    RAISE NOTICE 'All Stripe tables now have primary keys - row deletion should work properly';
  ELSE
    RAISE WARNING 'Some Stripe tables may still be missing primary keys';
  END IF;
END $$;