/*
  # Fix Stripe table auto-incrementing IDs

  1. Database Changes
    - Add auto-incrementing identity to `stripe_customers.id` column
    - Add auto-incrementing identity to `stripe_orders.id` column  
    - Add auto-incrementing identity to `stripe_subscriptions.id` column

  2. Purpose
    - Resolves "null value in column 'id'" constraint violations
    - Ensures proper record creation in Stripe webhook processing
    - Allows database to automatically generate primary key values

  3. Notes
    - Uses GENERATED BY DEFAULT AS IDENTITY for flexibility
    - Existing records (if any) will not be affected
    - New records will automatically get sequential ID values
*/

-- Add auto-incrementing identity to stripe_customers.id
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'stripe_customers' 
    AND column_name = 'id' 
    AND is_identity = 'YES'
  ) THEN
    ALTER TABLE public.stripe_customers 
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END $$;

-- Add auto-incrementing identity to stripe_orders.id
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'stripe_orders' 
    AND column_name = 'id' 
    AND is_identity = 'YES'
  ) THEN
    ALTER TABLE public.stripe_orders 
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END $$;

-- Add auto-incrementing identity to stripe_subscriptions.id
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'stripe_subscriptions' 
    AND column_name = 'id' 
    AND is_identity = 'YES'
  ) THEN
    ALTER TABLE public.stripe_subscriptions 
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END $$;